const shipments=[
 {id:'SHP-260923-128',date:'23 Sep 2026',destination:'Bandung',customer:'CV Sumber Makmur',product:'AMDK 600 ml · 420 dus',vehicle:'B 9124 FZ · A. Setiawan',time:'10.45',status:'Dalam perjalanan',tone:'blue'},
 {id:'SHP-260923-127',date:'23 Sep 2026',destination:'Semarang',customer:'PT Tirta Niaga',product:'AMDK 1.500 ml · 260 dus',vehicle:'D 8831 KC · R. Firmansyah',time:'12.30',status:'Disiapkan',tone:'amber'},
 {id:'SHP-260923-126',date:'23 Sep 2026',destination:'Cirebon',customer:'Toko Berkah Jaya',product:'AMDK gelas 240 ml · 180 dus',vehicle:'B 7442 GR · Y. Maulana',time:'09.20',status:'Terkirim',tone:'green'},
 {id:'SHP-260923-125',date:'23 Sep 2026',destination:'Tangerang',customer:'Grosir Anugerah',product:'AMDK 600 ml · 300 dus',vehicle:'B 6308 PN · H. Saputra',time:'11.10',status:'Dalam perjalanan',tone:'blue'},
 {id:'SHP-260923-124',date:'23 Sep 2026',destination:'Solo',customer:'UD Segar Abadi',product:'AMDK 19 L · 75 galon',vehicle:'H 1820 AT · B. Santoso',time:'13.00',status:'Perlu perhatian',tone:'red'}
];
const inventory=[
 {sku:'AM-600-24',name:'Jatiluhur Botol 600 ml',location:'Bekasi',stock:'470 dus',min:'500 dus',value:'Rp 28,2 jt',condition:'Di bawah minimum',tone:'red'},
 {sku:'AM-240-48',name:'Jatiluhur Gelas 240 ml',location:'Bandung',stock:'326 dus',min:'350 dus',value:'Rp 9,8 jt',condition:'Di bawah minimum',tone:'red'},
 {sku:'AM-19L-R',name:'Jatiluhur Galon 19 L',location:'Semarang',stock:'174 unit',min:'200 unit',value:'Rp 6,9 jt',condition:'Di bawah minimum',tone:'amber'},
 {sku:'AM-1500-12',name:'Jatiluhur Botol 1.500 ml',location:'Bekasi',stock:'1.280 dus',min:'400 dus',value:'Rp 76,8 jt',condition:'Aman',tone:'green'},
 {sku:'AM-330-24',name:'Jatiluhur Botol 330 ml',location:'Cirebon',stock:'840 dus',min:'300 dus',value:'Rp 25,2 jt',condition:'Aman',tone:'green'},
 {sku:'AM-600-24',name:'Jatiluhur Botol 600 ml',location:'Bandung',stock:'560 dus',min:'400 dus',value:'Rp 33,6 jt',condition:'Aman',tone:'green'}
];
const fleet=[
 {plate:'B 9124 FZ',kind:'Truk boks · 6 ton',driver:'Andi Setiawan',route:'Bekasi → Bandung',odo:'81.240 km',service:'12 Okt 2026',status:'Dalam perjalanan',tone:'blue'},
 {plate:'D 8831 KC',kind:'Truk boks · 4 ton',driver:'Rian Firmansyah',route:'Bekasi → Semarang',odo:'64.820 km',service:'30 Sep 2026',status:'Dalam perjalanan',tone:'blue'},
 {plate:'B 7442 GR',kind:'Engkel · 3 ton',driver:'Yusuf Maulana',route:'Cirebon → Bandung',odo:'44.150 km',service:'05 Okt 2026',status:'Siap berangkat',tone:'green'},
 {plate:'B 6308 PN',kind:'Truk boks · 6 ton',driver:'Hendra Saputra',route:'Bekasi → Tangerang',odo:'92.720 km',service:'25 Sep 2026',status:'Perlu inspeksi',tone:'red'},
 {plate:'H 1820 AT',kind:'Engkel · 3 ton',driver:'Budi Santoso',route:'Semarang → Solo',odo:'53.600 km',service:'07 Okt 2026',status:'Dalam perjalanan',tone:'blue'},
 {plate:'F 1832 MM',kind:'Pickup · 1 ton',driver:'Dedi Kurniawan',route:'Gudang Bandung',odo:'37.910 km',service:'18 Okt 2026',status:'Perawatan',tone:'amber'}
];
const finance=[
 {doc:'INV-EXP-0926-044',date:'22 Sep 2026',kind:'Jasa ekspedisi',vendor:'PT Lintas Jawa',value:'Rp 12.400.000',due:'30 Sep 2026',status:'Menunggu pembayaran',tone:'amber'},
 {doc:'BBM-0926-081',date:'22 Sep 2026',kind:'Bahan bakar',vendor:'SPBU Mitra Bekasi',value:'Rp 8.750.000',due:'Lunas',status:'Lunas',tone:'green'},
 {doc:'INV-MNT-0926-014',date:'20 Sep 2026',kind:'Perawatan armada',vendor:'Bengkel Utama',value:'Rp 6.250.000',due:'28 Sep 2026',status:'Menunggu verifikasi',tone:'blue'},
 {doc:'INV-EXP-0926-039',date:'19 Sep 2026',kind:'Jasa ekspedisi',vendor:'CV Angkut Cepat',value:'Rp 14.300.000',due:'27 Sep 2026',status:'Jatuh tempo dekat',tone:'red'},
 {doc:'BBM-0926-073',date:'18 Sep 2026',kind:'Bahan bakar',vendor:'SPBU Mitra Bandung',value:'Rp 5.920.000',due:'Lunas',status:'Lunas',tone:'green'}
];
const masters={produk:{title:'Produk & SKU',head:['SKU','NAMA PRODUK','KEMASAN','SATUAN','STATUS'],rows:[['AM-600-24','Jatiluhur Botol 600 ml','24 botol / dus','Dus','Aktif'],['AM-240-48','Jatiluhur Gelas 240 ml','48 gelas / dus','Dus','Aktif'],['AM-19L-R','Jatiluhur Galon 19 L','Isi ulang','Unit','Aktif'],['AM-1500-12','Jatiluhur Botol 1.500 ml','12 botol / dus','Dus','Aktif']]},gudang:{title:'Lokasi gudang',head:['KODE','NAMA LOKASI','KAPASITAS','PENANGGUNG JAWAB','STATUS'],rows:[['WH-BKS','Gudang Bekasi','10.000 unit','D. Kurniawan','Aktif'],['WH-BDG','Gudang Bandung','6.500 unit','R. Firmansyah','Aktif'],['WH-SMG','Gudang Semarang','5.000 unit','B. Santoso','Aktif'],['WH-CRB','Gudang Cirebon','4.000 unit','Y. Maulana','Aktif']]},armada:{title:'Armada & pengemudi',head:['NO. KENDARAAN','JENIS','PENGEMUDI UTAMA','KAPASITAS','STATUS'],rows:fleet.slice(0,4).map(x=>[x.plate,x.kind,x.driver,'4–6 ton',x.status])},mitra:{title:'Mitra & pelanggan',head:['KODE MITRA','NAMA ENTITAS','JENIS','WILAYAH','STATUS'],rows:[['C-0001','CV Sumber Makmur','Pelanggan','Bandung','Aktif'],['C-0002','PT Tirta Niaga','Pelanggan','Semarang','Aktif'],['E-0001','PT Lintas Jawa','Ekspedisi','Jawa','Aktif'],['S-0001','SPBU Mitra Bekasi','Pemasok','Bekasi','Aktif']]},akun:{title:'Akun biaya',head:['KODE AKUN','KATEGORI','PUSAT BIAYA','ANGGARAN TAHUNAN','STATUS'],rows:[['6101','Bahan bakar','Distribusi','Rp 265 jt','Aktif'],['6102','Jasa ekspedisi','Distribusi','Rp 176 jt','Aktif'],['6103','Perawatan armada','Armada','Rp 113 jt','Aktif'],['6104','Biaya tol & parkir','Distribusi','Rp 76 jt','Aktif']]},pengguna:{title:'Pengguna & peran',head:['ID PENGGUNA','NAMA','UNIT','PERAN','STATUS'],rows:[['USR-001','Operator Logistik','Operasi','Admin','Aktif'],['USR-002','Pengawas Gudang','Gudang','Supervisor','Aktif'],['USR-003','Koordinator Armada','Transportasi','Operator','Aktif'],['USR-004','Analis Keuangan','Keuangan','Pembaca','Aktif']]}};
const el=(id)=>document.getElementById(id);let toastTimer;
function toast(message){const t=el('toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function status(tone,text){return `<span class="status-pill pill-${tone}">${text}</span>`}
function renderRows(){el('shipmentRows').innerHTML=shipments.slice(0,4).map(s=>`<tr><td class="id-cell">${s.id}</td><td><b>${s.destination}</b><small>${s.customer}</small></td><td>${s.vehicle.split(' · ')[0]}<small>${s.vehicle.split(' · ')[1]}</small></td><td>${s.time}<small>${s.date}</small></td><td>${status(s.tone,s.status)}</td><td><button class="row-more" aria-label="Rincian">•••</button></td></tr>`).join('');
 el('expeditionRows').innerHTML=shipments.concat([{...shipments[0],id:'SHP-260923-123',destination:'Purwakarta',customer:'Toko Segar Jaya',status:'Terkirim',tone:'green'},{...shipments[2],id:'SHP-260923-122',destination:'Bogor',customer:'CV Mitra Niaga',status:'Tertahan',tone:'red'}]).map(s=>`<tr><td class="id-cell">${s.id}</td><td>${s.date}</td><td><b>${s.destination}</b><small>${s.customer}</small></td><td>${s.product}</td><td>${s.vehicle.split(' · ')[0]}<small>${s.vehicle.split(' · ')[1]}</small></td><td>${s.time}</td><td>${status(s.tone,s.status)}</td></tr>`).join('');
 el('inventoryRows').innerHTML=inventory.map(x=>`<tr><td class="id-cell">${x.sku}</td><td><b>${x.name}</b></td><td>${x.location}</td><td><b>${x.stock}</b></td><td>${x.min}</td><td>${x.value}</td><td>${status(x.tone,x.condition)}</td></tr>`).join('');
 el('fleetRows').innerHTML=fleet.map(x=>`<tr><td class="id-cell">${x.plate}</td><td>${x.kind}</td><td>${x.driver}</td><td>${x.route}</td><td>${x.odo}</td><td>${x.service}</td><td>${status(x.tone,x.status)}</td></tr>`).join('');
 el('financeRows').innerHTML=finance.map(x=>`<tr><td class="id-cell">${x.doc}</td><td>${x.date}</td><td>${x.kind}</td><td>${x.vendor}</td><td><b>${x.value}</b></td><td>${x.due}</td><td>${status(x.tone,x.status)}</td></tr>`).join('');
 el('criticalStock').innerHTML=inventory.filter(x=>x.tone!=='green').slice(0,3).map((x,i)=>`<div class="stock-item"><div class="stock-icon">${i===2?'◉':'▤'}</div><div class="stock-meta"><b>${x.name}</b><small>${x.location} · Minimum ${x.min}</small></div><div class="stock-count">${x.stock}<small>${x.condition}</small></div></div>`).join('');
 renderMaster('produk');}
function renderMaster(key){const m=masters[key];if(!m)return;el('masterTableTitle').textContent=m.title;el('masterHead').innerHTML=`<tr>${m.head.map(h=>`<th>${h}</th>`).join('')}</tr>`;el('masterRows').innerHTML=m.rows.map(row=>`<tr>${row.map((c,i)=>`<td>${i===0?`<span class="id-cell">${c}</span>`:i===1?`<b>${c}</b>`:c==='Aktif'?status('green','Aktif'):c}</td>`).join('')}</tr>`).join('');document.querySelectorAll('.master-card').forEach(c=>c.classList.toggle('selected',c.dataset.master===key));}
function navigate(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const active=document.querySelector(`.nav-item[data-view="${view}"]`);el('crumb').textContent=active?active.textContent.trim():view==='architecture'?'Arsitektur Data':'Ringkasan';document.querySelector('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',`#${view}`)}
function csvDownload(filename,headers,rows){const csv=[headers,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=filename;a.click();URL.revokeObjectURL(a.href);toast('CSV berhasil diunduh')}
function exportShip(){csvDownload('ringkasan-pengiriman.csv',['ID','Tanggal','Tujuan','Pelanggan','Muatan','Armada/Pengemudi','Waktu','Status'],shipments.map(s=>[s.id,s.date,s.destination,s.customer,s.product,s.vehicle,s.time,s.status]))}
function openModal(type){el('formType').value=type||'Pengiriman baru';el('modalTitle').textContent=type||'Catat transaksi';el('modalDesc').textContent=`Isi informasi ${String(type||'transaksi').toLowerCase()} untuk mencatat aktivitas operasional.`;el('formDate').value=new Date().toISOString().slice(0,10);el('modalBackdrop').classList.add('open')}
document.querySelectorAll('.nav-item').forEach(n=>n.addEventListener('click',()=>navigate(n.dataset.view)));document.querySelectorAll('[data-goto]').forEach(n=>n.addEventListener('click',()=>navigate(n.dataset.goto)));
document.querySelectorAll('.master-card').forEach(n=>n.addEventListener('click',()=>renderMaster(n.dataset.master)));
document.querySelectorAll('.generic-search').forEach(input=>input.addEventListener('input',()=>{const tbody=el(input.dataset.table);if(!tbody)return;const q=input.value.toLowerCase();[...tbody.rows].forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))}));
el('shipmentSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();[...el('shipmentRows').rows].forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))});
el('period').addEventListener('change',e=>{el('kpiShip').innerHTML=e.target.value==='today'?'128 <small>order</small>':e.target.value==='7'?'864 <small>order</small>':'3.420 <small>order</small>';toast(`Ringkasan disesuaikan: ${e.target.selectedOptions[0].text}`)});
el('exportBtn').addEventListener('click',exportShip);el('expExport').addEventListener('click',exportShip);el('stockExport').addEventListener('click',()=>csvDownload('kartu-stok.csv',['SKU','Produk','Lokasi','Stok','Minimum','Nilai','Kondisi'],inventory.map(x=>[x.sku,x.name,x.location,x.stock,x.min,x.value,x.condition])));
el('fleetExport').addEventListener('click',()=>csvDownload('armada.csv',['Nomor kendaraan','Jenis','Pengemudi','Rute/Lokasi','Odometer','Pemeriksaan berikutnya','Status'],fleet.map(x=>[x.plate,x.kind,x.driver,x.route,x.odo,x.service,x.status])));
el('financeExport').addEventListener('click',()=>csvDownload('biaya-pembiayaan.csv',['Nomor dokumen','Tanggal','Jenis biaya','Pemasok','Nilai','Jatuh tempo','Status'],finance.map(x=>[x.doc,x.date,x.kind,x.vendor,x.value,x.due,x.status])));
el('masterExport').addEventListener('click',()=>{const active=document.querySelector('.master-card.selected')?.dataset.master||'produk',m=masters[active];csvDownload(`data-master-${active}.csv`,m.head,m.rows)});
el('newShipment').addEventListener('click',()=>openModal('Pengiriman baru'));el('stockMove').addEventListener('click',()=>openModal('Mutasi barang'));el('addVehicle').addEventListener('click',()=>openModal('Kendaraan baru'));el('addMaster').addEventListener('click',()=>openModal('Data master baru'));
['closeModal','cancelModal'].forEach(id=>el(id).addEventListener('click',()=>el('modalBackdrop').classList.remove('open')));el('modalBackdrop').addEventListener('click',e=>{if(e.target===el('modalBackdrop'))el('modalBackdrop').classList.remove('open')});el('quickForm').addEventListener('submit',e=>{e.preventDefault();el('modalBackdrop').classList.remove('open');e.target.reset();toast('Pencatatan simulasi berhasil. Data belum tersimpan ke server.')});
el('menuBtn').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));el('bannerDismiss').addEventListener('click',()=>document.querySelector('.demo-banner').remove());el('nextRows').addEventListener('click',()=>navigate('expedition'));el('statusFilter').addEventListener('click',()=>toast('Filter status tersedia pada daftar Pengiriman.'));
document.querySelectorAll('.map-controls button').forEach((b,i)=>b.addEventListener('click',()=>{const svg=b.closest('.map-wrap').querySelector('.route-map');svg.style.transform=`scale(${i===0?1.12:.96})`;setTimeout(()=>svg.style.transform='',250)}));
el('currentDate').textContent=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric'}).format(new Date());renderRows();const hash=location.hash.replace('#','');if(hash&&document.getElementById(`view-${hash}`))navigate(hash);
